<?php

/**
 * Implements hook_apps_app_info().
 */
function openpublish_twitter_apps_app_info(){
  return array(
    'configure form' => 'openpublish_twitter_config_form',
  );
}

/**
 * Implements hook_menu().
 */
function openpublish_twitter_menu(){
  
  $items['admin/apps/openpublish/app/openpublish_twitter/more-boxes-help'] = array(
    'page callback' => 'openpublish_twitter_more_blocks_help',
    'access callback' => TRUE,
    'title' => 'More Blocks Help',
  );
  
  return $items;
}


/**
 * Implements hook_block_info().
 */
function openpublish_twitter_block_info(){
  $blocks = array();
  
  $blocks['openpublish_twitter_block'] = array(
    'info' => 'OpenPublish Twitter Block',
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function openpublish_twitter_block_view($delta = ''){
  $block = array();
  if($delta == 'openpublish_twitter_block'){
    $tweet_type = variable_get('openpublish_twitter_tweet_type', 'user');
    $num_tweets = variable_get('openpublish_twitter_num_tweets', 5);
    $twit_key = variable_get('openpublish_twitter_search', '@openpublish');
    
    $title = variable_get('openpublish_twitter_block_title', '');
    $block['subject'] = $title;
    $block['content'] = twitter_pull_render($twit_key, '<none>', $num_tweets);
  }
  
  return $block;
}


/**
 * Provides the configuration form for the app.
 */
function openpublish_twitter_config_form(){
  $form = array();
  drupal_add_css(drupal_get_path('module', 'openpublish_twitter') . '/css/openpublish_twitter_admin.css');
  
  //Vertical tabs fieldset
  $form['tabs'] = array(
    '#type' => 'vertical_tabs',
  );
  
  
  /*** Block form **/
  
  $form['tabs']['block'] = array(
    '#type' => 'fieldset',
    '#title' => 'Twitter Block',
    '#description' => 'Modify the twitter block\'s content and placement.',
    '#collapsible' => FALSE,
  );
  
  //Twitter Settings
  $form['tabs']['block']['twitter'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#title' => t('Twitter Settings'),
  );
  
  $form['tabs']['block']['twitter']['openpublish_twitter_search'] = array(
    '#type'           => 'textfield',
    '#title'          => 'Twitter search term',
    '#description'    => 'Enter either a username (@) or hashtag topic (#) to populate the block.',
    '#default_value'  => variable_get('openpublish_twitter_search', '@openpublish'),
  );
  
  //Display settings
  $form['tabs']['block']['display'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#title' => t('Display Settings'),
  );
  
  $form['tabs']['block']['display']['openpublish_twitter_block_title'] = array(
    '#type'           => 'textfield',
    '#title'          => 'Block title',
    '#description'    => 'The title of the twitter block. Leave empty for no title.',
    '#default_value'  => variable_get('openpublish_twitter_block_title', ''),
  );
  
  $form['tabs']['block']['display']['openpublish_twitter_num_tweets'] = array(
    '#type'           => 'textfield',
    '#title'          => 'Number of tweets',
    '#description'    => 'Select the number of tweets to show. Leave blank to configure this on a per-field basis.',
    '#size'           => 2,
    '#maxlength'      => 2,
    '#default_value'  => variable_get('openpublish_twitter_num_tweets', 5),
  );
  
  
  //Placement settings
  $form['tabs']['block']['placement'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#title' => t('Placement Settings'),
  );
  
  $form['tabs']['block']['placement']['openpublish_twitter_content_types'] = array(
    '#type'           => 'checkboxes',
    '#title'          => 'Content types',
    '#description'    => 'Select which content types the twitter block will display next to.',
    '#options'        => _node_types_build()->names,
    '#default_value'  => variable_get('openpublish_twitter_content_types', array()),
  );
  
  
  $regions = array(
    'content' => 'Content',
    'sidebar_first' => 'Sidebar (Left)',
    'sidebar_second' => 'Sidebar (Right)',
  );
  $form['tabs']['block']['placement']['openpublish_twitter_location'] = array(
    '#type'           => 'radios',
    '#title'          => 'Location',
    '#description'    => 'Select where the twitter block will be placed',
    '#options'        => $regions,
    '#default_value'  => variable_get('openpublish_twitter_location', 'content'),
  );
  
  $form['tabs']['block']['more_boxes_help'] = array(
    '#markup' => l('Need more Twitter blocks?', 'admin/apps/openpublish/app/openpublish_twitter/more-boxes-help'),
    '#weight' => 20,
  );
  
  
  
  /*** Field form ***/
  
  $form['tabs']['field'] = array(
    '#type' => 'fieldset',
    '#title' => 'Related Tweets Field',
    '#description' => 'Modify which content types can use the related tweets field, and display settings.',
    '#collapsible' => FALSE,
  );
  
  $form['tabs']['field']['openpublish_twitter_field_title'] = array(
    '#type' => 'textfield',
    '#title' => 'Display title',
    '#description' => 'Use &lt;none&gt; to display no title, or leave blank to customize on a per-field basis, with a default title of the expression.',
    '#default_value' => variable_get('openpublish_twitter_field_title'),
  );
  
  $form['tabs']['field']['openpublish_twitter_field_num_tweets'] = array(
    '#type'           => 'textfield',
    '#title'          => 'Number of tweets',
    '#description'    => 'Select the number of tweets to show. Leave blank to make configurations per field.',
    '#size'           => 2,
    '#maxlength'      => 2,
    '#default_value'  => variable_get('openpublish_twitter_field_num_tweets', 5),
  );
  
  //Get which content types have field_related_tweets, don't trust the variable.
  $fields = field_info_field('field_related_tweets');
  $fields = isset($fields['bundles']['node']) ? $fields['bundles']['node'] : array();
  
  $form['tabs']['field']['openpublish_twitter_field_content_types'] = array(
    '#type'           => 'checkboxes',
    '#title'          => 'Content types',
    '#description'    => 'Select which content types will get a related tweets field. You can use the edit links to make advanced configurations, but re-submitting this form may overrwrite some settings unless left blank.',
    '#options'        => _node_types_build()->names,
    '#default_value'  => $fields,
  );
  
  //Duplicate the checkboxes, and hide them. This is because we disable 
  //  existing fields, and disabled checkboxes don't get sent via POST.
  //Has to be hidden via CSS, since it's not a simple value that we can use #type => 'hidden' for
  $form['tabs']['field']['openpublish_twitter_field_content_types_existing'] = array(
    '#type'           => 'checkboxes',
    '#title'          => 'I\'m supposed to be hidden. Don\'t mess with me.',
    '#options'        => _node_types_build()->names,
    '#default_value'  => $fields,
  );
  
  //Provide links for field edit and display edit
  $field_links = array();
  foreach($fields as $field){
    $url = 'admin/structure/types/manage/'.str_replace('_', '-', $field);
    $options = array(
      'attributes' => array(
        'target' => '_blank',
      ),
    );
    $delete_options = array(
      'query' => array(
        'destination' => array_shift(drupal_get_destination()),
      ),
    );
    
    $links = array();
    $links['#prefix'] = '<div class="edit-links">';
    $links['edit_field'] = array(
      '#prefix' => '<div class="edit-field">',
      '#markup' => l('Edit Field', $url.'/fields/field_related_tweets', $options),
      '#suffix' => '</div>',
    );
    $links['edit_display'] = array(
      '#prefix' => '<div class="edit-display">',
      '#markup' => l('Edit Display', $url.'/display', $options),
      '#suffix' => '</div>',
    );
    $links['delete_field'] = array(
      '#prefix' => '<div class="delete">',
      '#markup' => l('Delete', $url.'/fields/field_related_tweets/delete', $delete_options),
      '#suffix' => '</div>',
    );
    $links['#suffix'] = '</div>';
    
    $form['tabs']['field']['openpublish_twitter_field_content_types'][$field]['#field_suffix'] = render($links);
    $form['tabs']['field']['openpublish_twitter_field_content_types'][$field]['#disabled'] = TRUE;
  }
  
  
  $form['tabs']['field']['openpublish_twitter_field_expression_types'] = array(
    '#type'           => 'checkboxes',
    '#title'          => 'Allowed Expression Types',
    '#description'    => 'Select which types of Twitter expressions can be used to populate the field. Select none if you wish to customize on a per-field basis.',
    '#default_value'  => variable_get('openpublish_twitter_field_expression_types', array()),
    '#options' => array(
      'username' => t('Usernames (@username)'),
      'list' => t('Lists (@username/list)'),
      'hashtag' => t('Hashtags (#topic)'),
      'search' => t('Searches'),
    ),
  );
  
  
  
  $form['#submit'][] = 'openpublish_twitter_config_form_submit';
  
  return system_settings_form($form);
}

/**
 * Submit handler for the app config form.
 */
function openpublish_twitter_config_form_submit($form, $form_state){

  /*** Block stuff ***/

  $module = 'openpublish_twitter';
  $block = 'openpublish_twitter_block';
  $context = context_load('openpublish_twitter');
  $region = $form_state['values']['openpublish_twitter_location'];
  
  //If no context was found, we'll create the initial one. This isn't done in features because it
  //can change with the config form, and we don't want a constantly overridden context.
  if(!$context){
    $context = new stdclass();
    $context->name = 'openpublish_twitter';
    $context->description = 'Places the OpenPublish Twitter block on various content types.';
    $context->tag = 'OpenPublish Twitter';
    $context->condition_mode = 0;
    $context->table = 'context';
    $context->type = 'Normal';
    $context->export_type = 1;
  }
  
  $context->conditions = array(
    'node' => array(
      'values' => $form_state['values']['openpublish_twitter_content_types'],
      'options' => array(
        'node_form' => 0,
      ),
    )
  );
  $context->reactions = array(
    'block' => array(
      'blocks' => array(
        $module.'-'.$block => array(
          'module' => $module,
          'delta' => $block,
          'region' => $region,
          'weight' => 0,
        ),
      ),
    ),
  );
  
  context_save($context);
  
  
  /*** Field stuff ***/
  
  $twit_fields = field_info_field('field_related_tweets');
  if(!empty($twit_fields)){
    $twit_fields = isset($twit_fields['bundles']['node']) ? $twit_fields['bundles']['node'] : array();
  }
  else{
    //Create the base field
    field_create_field(array(
      'field_name' => 'field_related_tweets',
      'type' => 'text'
    ));
    $twit_fields = array();
  }
  
  //Combine the 2 checkbox fields
  foreach($form_state['values']['openpublish_twitter_field_content_types'] as $field => $enabled){
    if(!empty($form_state['values']['openpublish_twitter_field_content_types_existing'][$field])){
      $form_state['values']['openpublish_twitter_field_content_types'][$field] = $field;
    }
  }
  
  foreach($form_state['values']['openpublish_twitter_field_content_types'] as $type => $enable){
    if(!empty($enable)){
      //Get the current settings, if it has any.
      $instance = field_read_instance('node', 'field_related_tweets', $type);
      if(!$instance){
        $instance = array();
      }
    
      $instance = $instance + array(
        'field_name' => 'field_related_tweets',
        'entity_type' => 'node',
        'bundle' => $type,
        'label' => 'Related Tweets',
        'widget' => array(
          'type' => 'twitterfield',
        ),
        'display' => array(
          'default' => array(
            'type' => 'twitterfield_twitter_pull'
          ),
        ),
      );
      
      //Only set it if it's got any values, otherwise leave it up to the admin to set it per field.
      if(!empty($form_state['values']['openpublish_twitter_field_expression_types'])){
        $instance['widget']['settings']['allowed_types'] = $form_state['values']['openpublish_twitter_field_expression_types'];
      }
      if(!empty($form_state['values']['openpublish_twitter_field_num_tweets'])){
        $instance['display']['default']['settings']['items'] = $form_state['values']['openpublish_twitter_field_num_tweets'];
      }
      if(!empty($form_state['values']['openpublish_twitter_field_title'])){
        $instance['display']['default']['settings']['title'] = $form_state['values']['openpublish_twitter_field_title'];
      }
      
      //Only set if description isn't set, or still contains the default description text and may need updating.
      $description = 'A twitter expression to get tweets from, such as ';
      if(empty($instance['description']) || stristr($instance['description'], $description)){
        $examples = array();
        foreach($form_state['values']['openpublish_twitter_field_expression_types'] as $expression){
          //Intentionally in numeric order
          if($expression == 'username'){
            $examples[0] = '@username';
          }
          elseif($expression == 'list'){
            $examples[1] = '@username/list';
          }
          elseif($expression == 'hashtag'){
            $examples[2] = '#topic';
          }
          else{
            $examples[3] = 'any search term';
          }
        }
        //Append 'or' to the last example
        $lastkey = array_pop(array_keys($examples));
        $examples[$lastkey] = 'or '.$examples[$lastkey];
        
        $instance['description'] = $description.implode($examples, ', ');
      }
    
      if(in_array($type, $twit_fields)){
        field_update_instance($instance);
      }
      else{
        field_create_instance($instance);
      }
    }
  }
}


/**
 * Page callback for admin/apps/openpublish/app/openpublish_twitter/more-boxes-help
 *
 * Just spits out plain html that instructs the user on how to make and place twitter_pull blocks.
 */
function openpublish_twitter_more_blocks_help(){
  $path = drupal_get_path('module', 'openpublish_twitter');
  $text = '
  <style>
    p, h1, h2, h3 {margin: 20px;}
    h1 {font-size: 28px;}
    h2 {font-size: 20px;}
    img {
      border: 1px solid #AAA;
      margin: 10px;
      float: left;
      max-width: 450px;
    }
  </style>
  
  <h1 id="#page-title">So, you need more Twitter blocks?</h1>
  <p>While this app does not provide a nice UI for creating and placing multiple twitter blocks, it does utilize 2 modules which will give you the power to do: '.l('twitter_pull', 'http://drupal.org/project/twitter_pull/').', and '.l('context', 'http://drupal.org/project/context/').'.</p>
  
  <h2>Creating the block</h2>
  <p>With twitter pull, you can make as many twitter blocks as you\'d like over at the '.l('add twitter pull block', 'admin/structure/block/box-add/twitter').' screen. It asks for a few more fields than OpenPublish Twitter asks for, such as the machine name which is a unique identifier name, and a description, which is the display name of the block in various menus. Make sure it\'s descriptive, i.e. "@OpenPublish box" and not "My twitter block".</p>
  
  <h2>Placing the block</h2>
  
  <p>Once you\'ve configured the box to your liking, you\'ll need to set up where to place it. This can be done in 2 ways.</p>
  
  <div class="clearfix">
  <img src="/'.$path.'/images/help-block-placement.png"></img>
  
  <h2>Via Blocks</h2>
  <p>The first and simplest way to place the block is by navigating to the block you just created, which should be listed on '.l('this page', 'admin/structure/block').', and going to the configure screen. You\'ll see a few new things there you didn\'t see at the block creation screen. The region settings options, which is where you specify where the block will go, and the vertical tabs at the bottom, which is where you will specify when the block should show up.</p>
  
  </div>
  
  <div class="clearfix">
  <img src="/'.$path.'/images/help-context.png"></img>
  
  <h2>Via Context</h2>
  <p>The second option is to use contexts. Contexts are a robust way of having your page\'s layout change based on conditions. You can find the context configuration screen '.l('here', 'admin/structure/context').'. You can either leverage an existing context provided by OpenPublish, or create your own for placing the twitter block.</p>
  
  <p>First, we\'ll cover creating your own. Hit "Add" at the top of the page, and name your context. Fill out the name, which must be in the same format as the block machine name, and select your condition. As you can see here, there are many more options than on the block placement tabs. Most of these are fairly self explanatory.</p>
  
  <p>For placing the block, which is the same whether or not you created your own context, you must add a block reaction. Select the twitter block you created before from the list on the right, and click "Add" on a region that you want the block to be placed. I suggest you choose Content, Sidebar First, or Sidebar Second.</p>
  
  </div>
  
  <p>And there you have it! Your block should be placed wherever you configured it to be.</p>';
  
  return $text;
}